### ISSUE TITLE
Experiment data file exists pop-up

### ISSUE THREAD

**Issue by jwassenburg** [NynkeDekkerLab/BeadTracker#16]
The option to choose another datafile location if the current name is already taken does not work. Instead, even when choosing another location, the old datafile will still be overwritten.
The only safe option is to cancel and manually choose another location before starting the experiment again.

This happens at the start of TrackerMain.vi.

**Comment by daimonie** [comment]
Prognosis: The issue seems quite clear. 

The ResultManager is instantiated through dll::make_rm before the popup, and is not changed afterwards.

**Comment by daimonie** [comment]
Resolution: Actually far simpler than I'd figured.

The VI requests the configuration. It then calls a subvi to verify settings. This subVI is passed the shallow copy of the configuration. If it changes, it is not updated.

As a result, all you needed to do was link the updated result. I've changed the VerifyMeasureConfig subVI to have an input/output configuration terminal. The ExperimentProgramUI.vi is edited to make sure it uses this. On Sam's setup, there is currently an indicator displaying the experiment name, which could be convenient. I will have to verify if he thinks it should be there for verification of the experiment name.
