### ISSUE TITLE
Frame timestamps

### ISSUE THREAD

**Issue by jwassenburg** [NynkeDekkerLab/BeadTracker#2]
Data frame timestamps do not always match the camera framerate.
Some deviation is always seen but expected. However, when the memory overloads during tracking (i.e. too many regions/s), the data file can sometimes even go out of sync.

**Comment by jwassenburg** [comment]
This seems to be influenced by two separate issues:
1. The QTrk tracking queue is full. This causes the frames to be added to the queue slower than the frames are captured. The display in TrackerMain.vi displays the amount of frames tracked per second, not captured per second.
2. The camera settings do not work very well. The maximum field of view size and exposure time for any desired framerate have to be determined empirically. If LabVIEW has settings that the camera can't handle, the framerate defaults to 25 with whatever exposure time was chosen (it seems, see ticket #3)

**Comment by daimonie** [comment]
When the memory overloads during tracking, there are various other issues with data analysis. As a result, I would say that this is a result of improper experiment settings and is resolved by making sure this doesn't happen, rather than going out on a limb to fix a bug that shouldn't ever occur.
