### ISSUE TITLE
Setting camera settings

### ISSUE THREAD

**Issue by jwassenburg** [NynkeDekkerLab/BeadTracker#3]
BeadTrackerMain.vi -> Camera settings
Setting and updating the camera settings does not work. Updates do not go through to the camera drivers for Dalsa cameras.

**Comment by jwassenburg** [comment]
Richard: 
It works sometimes, depending on the setup. In most setups all settings can be changed by the NIMax, but not for the 12MP cameras. Then it has to be done by labview and seems to work.
In addition, it would be nice to have the camera settings (mainly frequency) in the info file. 
Apparently the settings window does not appear on all setups.

**Comment by jwassenburg** [comment]
Mariana:
The settings seem to update once a LUT is started (D018R)

**Comment by daimonie** [comment]
Made an attempt at fixing this. Needs to be tested.
