### ISSUE TITLE
Closing pop-up windows

### ISSUE THREAD

**Issue by jwassenburg** [NynkeDekkerLab/BeadTracker#4]
Closing pop-up windows through the cross rather than the intended button freezes the program. Is this fixable?

**Comment by daimonie** [comment]
Use show terminals on a popup and set its true/false allow close terminal. Just remove the option to be safe. (otherwise, yes, it will cause an error because the dialogue is unresolved and your flow short circuits).

**Comment by daimonie** [comment]
Correction. The dialog I know how to find is VerifyMeasureConfig.vi, and this one has the close window correctly wired.

**Comment by daimonie** [comment]
Louis says the relevant popups are:

- Camera Settings
- QTrk settings

These are subvi's. Let's check it out.

**Comment by daimonie** [comment]
Let's just remove the option. In QTrk settings, go to the relevant VI for QTrk settings and use File -> VI properties -> Window Appearance -> Costumise -> and make sure the close/min/etc buttons are disabled.

For the camera settings, this is slightly more complicated. It seems thesse are specific VI's called through a generic interface, each and every VI likely has to be changed. However, it might be different; need to verify on a setup.

**Comment by daimonie** [comment]
Haven't checked Camera VI's yet, but went over all others. (3-1-17)

**Comment by daimonie** [comment]
Test succesful
