### ISSUE TITLE
Reference bead # when discarding beads

### ISSUE THREAD

**Issue by jwassenburg** [NynkeDekkerLab/BeadTracker#5]
When a bead is discarded the reference bead number should decrease if the discarded bead was before the current reference bead.
If the discarded bead was the reference bead, disable subtract reference.

**Comment by daimonie** [comment]
Seems simple enough. Labview time.

**Comment by daimonie** [comment]
Should be fixed. Created a local variable from the reference bead number (bottom below traces).

Read from local variable, compare to discarded bead number, if smaller decrease reference number and save it.
